#!/usr/bin/env python3
"""
BeatGuessr Quick Data Generator
Generates song data using the fallback database with simulated preview URLs.
Use this for quick testing when the full scraper takes too long.
"""

import json
import hashlib
from pathlib import Path
from datetime import datetime

SCRIPT_DIR = Path(__file__).parent
CONTEXTS_FILE = SCRIPT_DIR / "contexts.json"
OUTPUT_FILE = SCRIPT_DIR.parent / "data" / "songs.json"


# Load contexts
def load_contexts():
    if CONTEXTS_FILE.exists():
        with open(CONTEXTS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


# Fallback database - popular songs from German charts
FALLBACK_DB = {
    1960: [
        ("Marina", "Rocco Granata"),
        ("Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini", "Brian Hyland"),
        ("Only the Lonely", "Roy Orbison"),
        ("Save the Last Dance for Me", "The Drifters"),
        ("Sailor", "Petula Clark"),
        ("Good Timin'", "Jimmy Jones"),
        ("Schöner fremder Mann", "Connie Francis"),
        ("Unter fremden Sternen", "Freddy Quinn"),
        ("Seemann", "Lolita"),
        ("Pigalle", "Bill Ramsey"),
    ],
    1961: [
        ("Wheels", "The String-A-Longs"),
        ("Wooden Heart", "Elvis Presley"),
        ("Blue Moon", "The Marcels"),
        ("Stand by Me", "Ben E. King"),
        ("Exodus", "Ferrante & Teicher"),
        ("Wir wollen niemals auseinandergehn", "Heidi Brühl"),
        ("Hundert Mann und ein Befehl", "Freddy Quinn"),
        ("Rote Lippen soll man küssen", "Cliff Richard"),
        ("Unsere Heimat", "Lolita"),
        ("La Paloma", "Freddy Quinn"),
    ],
    1962: [
        ("Stranger on the Shore", "Acker Bilk"),
        ("I Can't Stop Loving You", "Ray Charles"),
        ("The Twist", "Chubby Checker"),
        ("Roses Are Red", "Bobby Vinton"),
        ("Speedy Gonzales", "Pat Boone"),
        ("Junge, komm bald wieder", "Freddy Quinn"),
        ("Ich zähle täglich meine Sorgen", "Peter Alexander"),
        ("Da sprach der alte Häuptling", "Gus Backus"),
        ("Zwei kleine Italiener", "Conny Froboess"),
        ("Moon River", "Danny Williams"),
    ],
    1963: [
        ("She Loves You", "The Beatles"),
        ("From Me to You", "The Beatles"),
        ("I Like It", "Gerry and the Pacemakers"),
        ("You're the Devil in Disguise", "Elvis Presley"),
        ("Sukiyaki", "Kyu Sakamoto"),
        ("Schuld war nur der Bossa Nova", "Manuela"),
        ("Wini Wini", "Caterina Valente"),
        ("Ich will 'nen Cowboy als Mann", "Gitte"),
        ("Spanish Eyes", "Al Martino"),
        ("Be My Baby", "The Ronettes"),
    ],
    1964: [
        ("I Want to Hold Your Hand", "The Beatles"),
        ("A Hard Day's Night", "The Beatles"),
        ("I Feel Fine", "The Beatles"),
        ("Oh, Pretty Woman", "Roy Orbison"),
        ("House of the Rising Sun", "The Animals"),
        ("Das macht die Liebe allein", "Peter Alexander"),
        ("Memphis Tennessee", "Chuck Berry"),
        ("Baby Love", "The Supremes"),
        ("Dancing in the Street", "Martha and the Vandellas"),
        ("Leader of the Pack", "The Shangri-Las"),
    ],
    1965: [
        ("Help!", "The Beatles"),
        ("Satisfaction", "The Rolling Stones"),
        ("Yesterday", "The Beatles"),
        ("Mr. Tambourine Man", "The Byrds"),
        ("My Generation", "The Who"),
        ("King of the Road", "Roger Miller"),
        ("Wooly Bully", "Sam the Sham"),
        ("Get Off of My Cloud", "The Rolling Stones"),
        ("Stop! In the Name of Love", "The Supremes"),
        ("I Got You Babe", "Sonny & Cher"),
    ],
    1966: [
        ("Yellow Submarine", "The Beatles"),
        ("Paint It Black", "The Rolling Stones"),
        ("Good Vibrations", "The Beach Boys"),
        ("River Deep Mountain High", "Ike & Tina Turner"),
        ("Strangers in the Night", "Frank Sinatra"),
        ("These Boots Are Made for Walkin'", "Nancy Sinatra"),
        ("Monday Monday", "The Mamas & The Papas"),
        ("Sunny", "Bobby Hebb"),
        ("Wild Thing", "The Troggs"),
        ("Last Train to Clarksville", "The Monkees"),
    ],
    1967: [
        ("All You Need Is Love", "The Beatles"),
        ("Let's Spend the Night Together", "The Rolling Stones"),
        ("Light My Fire", "The Doors"),
        ("A Whiter Shade of Pale", "Procol Harum"),
        ("San Francisco", "Scott McKenzie"),
        ("Somethin' Stupid", "Nancy & Frank Sinatra"),
        ("Puppet on a String", "Sandie Shaw"),
        ("The Letter", "The Box Tops"),
        ("Waterloo Sunset", "The Kinks"),
        ("Happy Together", "The Turtles"),
    ],
    1968: [
        ("Hey Jude", "The Beatles"),
        ("Jumpin' Jack Flash", "The Rolling Stones"),
        ("Delilah", "Tom Jones"),
        ("Hello I Love You", "The Doors"),
        ("Those Were the Days", "Mary Hopkin"),
        ("Ob-La-Di, Ob-La-Da", "The Beatles"),
        ("Congratulations", "Cliff Richard"),
        ("Lady Madonna", "The Beatles"),
        ("Mrs. Robinson", "Simon & Garfunkel"),
        ("Born to Be Wild", "Steppenwolf"),
    ],
    1969: [
        ("Sugar Sugar", "The Archies"),
        ("Honky Tonk Women", "The Rolling Stones"),
        ("Give Peace a Chance", "John Lennon"),
        ("I Heard It Through the Grapevine", "Marvin Gaye"),
        ("Get Back", "The Beatles"),
        ("In the Year 2525", "Zager and Evans"),
        ("Bad Moon Rising", "Creedence Clearwater Revival"),
        ("Something", "The Beatles"),
        ("Come Together", "The Beatles"),
        ("Suspicious Minds", "Elvis Presley"),
    ],
    1970: [
        ("Let It Be", "The Beatles"),
        ("Bridge over Troubled Water", "Simon & Garfunkel"),
        ("The Wonder of You", "Elvis Presley"),
        ("All Right Now", "Free"),
        ("Paranoid", "Black Sabbath"),
        ("Layla", "Derek and the Dominos"),
        ("Lola", "The Kinks"),
        ("In the Summertime", "Mungo Jerry"),
        ("Venus", "Shocking Blue"),
        ("Spirit in the Sky", "Norman Greenbaum"),
    ],
    1971: [
        ("Imagine", "John Lennon"),
        ("Brown Sugar", "The Rolling Stones"),
        ("Stairway to Heaven", "Led Zeppelin"),
        ("Riders on the Storm", "The Doors"),
        ("Chirpy Chirpy Cheep Cheep", "Middle of the Road"),
        ("My Sweet Lord", "George Harrison"),
        ("Maggie May", "Rod Stewart"),
        ("Get It On", "T. Rex"),
        ("Hot Love", "T. Rex"),
        ("Ich möchte mit dir leben", "Marianne Rosenberg"),
    ],
    1972: [
        ("American Pie", "Don McLean"),
        ("Metal Guru", "T. Rex"),
        ("School's Out", "Alice Cooper"),
        ("Without You", "Harry Nilsson"),
        ("Telegram Sam", "T. Rex"),
        ("Son of My Father", "Chicory Tip"),
        ("Rock and Roll", "Led Zeppelin"),
        ("Popcorn", "Hot Butter"),
        ("Daddy Cool", "Boney M."),
        ("Crocodile Rock", "Elton John"),
    ],
    1973: [
        ("Angie", "The Rolling Stones"),
        ("Smoke on the Water", "Deep Purple"),
        ("Tie a Yellow Ribbon", "Tony Orlando & Dawn"),
        ("Blockbuster", "Sweet"),
        ("The Jean Genie", "David Bowie"),
        ("Cum On Feel the Noize", "Slade"),
        ("Radar Love", "Golden Earring"),
        ("Killing Me Softly", "Roberta Flack"),
        ("Get Down", "Gilbert O'Sullivan"),
        ("Dancing on a Saturday Night", "Barry Blue"),
    ],
    1974: [
        ("Waterloo", "ABBA"),
        ("Tiger Feet", "Mud"),
        ("Seasons in the Sun", "Terry Jacks"),
        ("Rock Your Baby", "George McCrae"),
        ("Billy Don't Be a Hero", "Paper Lace"),
        ("The Six Teens", "Sweet"),
        ("Kung Fu Fighting", "Carl Douglas"),
        ("Sugar Baby Love", "The Rubettes"),
        ("Killer Queen", "Queen"),
        ("Radar Love", "Golden Earring"),
    ],
    1975: [
        ("Bohemian Rhapsody", "Queen"),
        ("SOS", "ABBA"),
        ("Mamma Mia", "ABBA"),
        ("Lady Marmalade", "LaBelle"),
        ("January", "Pilot"),
        ("Jive Talkin'", "Bee Gees"),
        ("I'm Not in Love", "10cc"),
        ("Sailing", "Rod Stewart"),
        ("That's the Way I Like It", "KC & the Sunshine Band"),
        ("Fame", "David Bowie"),
    ],
    1976: [
        ("Fernando", "ABBA"),
        ("Dancing Queen", "ABBA"),
        ("Don't Go Breaking My Heart", "Elton John & Kiki Dee"),
        ("December 1963", "The Four Seasons"),
        ("I Love to Love", "Tina Charles"),
        ("Save Your Kisses for Me", "Brotherhood of Man"),
        ("Mississippi", "Pussycat"),
        ("If You Leave Me Now", "Chicago"),
        ("Money Money Money", "ABBA"),
        ("Anarchy in the UK", "Sex Pistols"),
    ],
    1977: [
        ("Hotel California", "Eagles"),
        ("Stayin' Alive", "Bee Gees"),
        ("We Are the Champions", "Queen"),
        ("Don't Cry for Me Argentina", "Julie Covington"),
        ("Knowing Me Knowing You", "ABBA"),
        ("The Name of the Game", "ABBA"),
        ("I Feel Love", "Donna Summer"),
        ("Ma Baker", "Boney M."),
        ("Daddy Cool", "Boney M."),
        ("Rivers of Babylon", "Boney M."),
    ],
    1978: [
        ("Night Fever", "Bee Gees"),
        ("Rivers of Babylon", "Boney M."),
        ("You're the One That I Want", "John Travolta & Olivia Newton-John"),
        ("Take a Chance on Me", "ABBA"),
        ("Summer Nights", "John Travolta & Olivia Newton-John"),
        ("Three Times a Lady", "Commodores"),
        ("Rasputin", "Boney M."),
        ("Mary's Boy Child", "Boney M."),
        ("Y.M.C.A.", "Village People"),
        ("Heart of Glass", "Blondie"),
    ],
    1979: [
        ("I Will Survive", "Gloria Gaynor"),
        ("Don't Stop Me Now", "Queen"),
        ("Another Brick in the Wall", "Pink Floyd"),
        ("Tragedy", "Bee Gees"),
        ("Chiquitita", "ABBA"),
        ("Gimme! Gimme! Gimme!", "ABBA"),
        ("Video Killed the Radio Star", "The Buggles"),
        ("Message in a Bottle", "The Police"),
        ("Pop Muzik", "M"),
        ("Ring My Bell", "Anita Ward"),
    ],
    1980: [
        ("Super Trouper", "ABBA"),
        ("The Winner Takes It All", "ABBA"),
        ("Call Me", "Blondie"),
        ("Funkytown", "Lipps Inc."),
        ("Another One Bites the Dust", "Queen"),
        ("Woman in Love", "Barbra Streisand"),
        ("Upside Down", "Diana Ross"),
        ("Don't Stand So Close to Me", "The Police"),
        ("Ashes to Ashes", "David Bowie"),
        ("Master Blaster", "Stevie Wonder"),
    ],
    1981: [
        ("Don't You Want Me", "The Human League"),
        ("Tainted Love", "Soft Cell"),
        ("Under Pressure", "Queen & David Bowie"),
        ("Vienna", "Ultravox"),
        ("Super Freak", "Rick James"),
        ("Endless Love", "Diana Ross & Lionel Richie"),
        ("Bette Davis Eyes", "Kim Carnes"),
        ("Start Me Up", "The Rolling Stones"),
        ("Every Little Thing She Does Is Magic", "The Police"),
        ("One Day in Your Life", "Michael Jackson"),
    ],
    1982: [
        ("The Lion Sleeps Tonight", "Tight Fit"),
        ("Eye of the Tiger", "Survivor"),
        ("Come On Eileen", "Dexys Midnight Runners"),
        ("Da Da Da", "Trio"),
        ("I Love Rock 'n' Roll", "Joan Jett"),
        ("Planet Earth", "Duran Duran"),
        ("Save a Prayer", "Duran Duran"),
        ("Africa", "Toto"),
        ("Down Under", "Men at Work"),
        ("I Ran", "A Flock of Seagulls"),
    ],
    1983: [
        ("99 Luftballons", "Nena"),
        ("Billie Jean", "Michael Jackson"),
        ("Beat It", "Michael Jackson"),
        ("Total Eclipse of the Heart", "Bonnie Tyler"),
        ("Karma Chameleon", "Culture Club"),
        ("Every Breath You Take", "The Police"),
        ("Sweet Dreams", "Eurythmics"),
        ("Flashdance", "Irene Cara"),
        ("Codo", "DÖF"),
        ("Major Tom", "Peter Schilling"),
    ],
    1984: [
        ("Relax", "Frankie Goes to Hollywood"),
        ("Wake Me Up Before You Go-Go", "Wham!"),
        ("Like a Virgin", "Madonna"),
        ("I Just Called to Say I Love You", "Stevie Wonder"),
        ("Footloose", "Kenny Loggins"),
        ("Purple Rain", "Prince"),
        ("Jump", "Van Halen"),
        ("When Doves Cry", "Prince"),
        ("Two Tribes", "Frankie Goes to Hollywood"),
        ("Hello", "Lionel Richie"),
    ],
    1985: [
        ("Take On Me", "a-ha"),
        ("We Are the World", "USA for Africa"),
        ("The Power of Love", "Huey Lewis and the News"),
        ("Live Is Life", "Opus"),
        ("Everybody Wants to Rule the World", "Tears for Fears"),
        ("Material Girl", "Madonna"),
        ("Running Up That Hill", "Kate Bush"),
        ("You Spin Me Round", "Dead or Alive"),
        ("I Want to Know What Love Is", "Foreigner"),
        ("Money for Nothing", "Dire Straits"),
    ],
    1986: [
        ("Take My Breath Away", "Berlin"),
        ("The Final Countdown", "Europe"),
        ("Walk Like an Egyptian", "The Bangles"),
        ("Living on a Prayer", "Bon Jovi"),
        ("Papa Don't Preach", "Madonna"),
        ("True Blue", "Madonna"),
        ("West End Girls", "Pet Shop Boys"),
        ("Rock Me Amadeus", "Falco"),
        ("Jeanny", "Falco"),
        ("Venus", "Bananarama"),
    ],
    1987: [
        ("Never Gonna Give You Up", "Rick Astley"),
        ("La Bamba", "Los Lobos"),
        ("I Wanna Dance with Somebody", "Whitney Houston"),
        ("With or Without You", "U2"),
        ("Livin' on a Prayer", "Bon Jovi"),
        ("Bad", "Michael Jackson"),
        ("Alone", "Heart"),
        ("Faith", "George Michael"),
        ("Nothing's Gonna Stop Us Now", "Starship"),
        ("Here I Go Again", "Whitesnake"),
    ],
    1988: [
        ("Sweet Child O' Mine", "Guns N' Roses"),
        ("Need You Tonight", "INXS"),
        ("Father Figure", "George Michael"),
        ("Together Forever", "Rick Astley"),
        ("Get Outta My Dreams", "Billy Ocean"),
        ("I Think We're Alone Now", "Tiffany"),
        ("I Should Be So Lucky", "Kylie Minogue"),
        ("The Loco-Motion", "Kylie Minogue"),
        ("One More Try", "George Michael"),
        ("Desire", "U2"),
    ],
    1989: [
        ("Like a Prayer", "Madonna"),
        ("Eternal Flame", "The Bangles"),
        ("Ride on Time", "Black Box"),
        ("Lambada", "Kaoma"),
        ("Wind of Change", "Scorpions"),
        ("Swing the Mood", "Jive Bunny"),
        ("Right Here Waiting", "Richard Marx"),
        ("Straight Up", "Paula Abdul"),
        ("She Drives Me Crazy", "Fine Young Cannibals"),
        ("Toy Soldiers", "Martika"),
    ],
    1990: [
        ("Nothing Compares 2 U", "Sinéad O'Connor"),
        ("Vogue", "Madonna"),
        ("Ice Ice Baby", "Vanilla Ice"),
        ("U Can't Touch This", "MC Hammer"),
        ("Tom's Diner", "Suzanne Vega"),
        ("The Power", "Snap!"),
        ("Killer", "Adamski"),
        ("Sacrifice", "Elton John"),
        ("Vision of Love", "Mariah Carey"),
        ("Enjoy the Silence", "Depeche Mode"),
    ],
    1991: [
        ("(Everything I Do) I Do It for You", "Bryan Adams"),
        ("Smells Like Teen Spirit", "Nirvana"),
        ("Wind of Change", "Scorpions"),
        ("Black or White", "Michael Jackson"),
        ("Losing My Religion", "R.E.M."),
        ("Sadeness", "Enigma"),
        ("The One and Only", "Chesney Hawkes"),
        ("More Than Words", "Extreme"),
        ("Gonna Make You Sweat", "C+C Music Factory"),
        ("Rush Rush", "Paula Abdul"),
    ],
    1992: [
        ("I Will Always Love You", "Whitney Houston"),
        ("Rhythm Is a Dancer", "Snap!"),
        ("End of the Road", "Boyz II Men"),
        ("November Rain", "Guns N' Roses"),
        ("Jump Around", "House of Pain"),
        ("Under the Bridge", "Red Hot Chili Peppers"),
        ("Bohemian Rhapsody", "Queen"),
        ("Finally", "CeCe Peniston"),
        ("Save the Best for Last", "Vanessa Williams"),
        ("Baby Got Back", "Sir Mix-a-Lot"),
    ],
    1993: [
        ("I'd Do Anything for Love", "Meat Loaf"),
        ("What Is Love", "Haddaway"),
        ("All That She Wants", "Ace of Base"),
        ("The Sign", "Ace of Base"),
        ("Mr. Vain", "Culture Beat"),
        ("Informer", "Snow"),
        ("Dreamlover", "Mariah Carey"),
        ("Fields of Gold", "Sting"),
        ("No Limit", "2 Unlimited"),
        ("Runaway Train", "Soul Asylum"),
    ],
    1994: [
        ("Love Is All Around", "Wet Wet Wet"),
        ("The Sign", "Ace of Base"),
        ("Cotton Eye Joe", "Rednex"),
        ("Zombie", "The Cranberries"),
        ("All I Wanna Do", "Sheryl Crow"),
        ("The Power of Love", "Céline Dion"),
        ("Saturday Night", "Whigfield"),
        ("Stay", "Lisa Loeb"),
        ("Regulate", "Warren G & Nate Dogg"),
        ("Return to Innocence", "Enigma"),
    ],
    1995: [
        ("Gangsta's Paradise", "Coolio"),
        ("Wonderwall", "Oasis"),
        ("Waterfalls", "TLC"),
        ("Kiss from a Rose", "Seal"),
        ("Fantasy", "Mariah Carey"),
        ("Scatman", "Scatman John"),
        ("I'll Be There for You", "The Rembrandts"),
        ("You Oughta Know", "Alanis Morissette"),
        ("Earth Song", "Michael Jackson"),
        ("Boombastic", "Shaggy"),
    ],
    1996: [
        ("Macarena", "Los del Río"),
        ("Killing Me Softly", "Fugees"),
        ("Wannabe", "Spice Girls"),
        ("How Deep Is Your Love", "Take That"),
        ("I Believe I Can Fly", "R. Kelly"),
        ("Don't Look Back in Anger", "Oasis"),
        ("Children", "Robert Miles"),
        ("Fastlove", "George Michael"),
        ("Missing", "Everything but the Girl"),
        ("Ready or Not", "Fugees"),
    ],
    1997: [
        ("Candle in the Wind 1997", "Elton John"),
        ("MMMBop", "Hanson"),
        ("Barbie Girl", "Aqua"),
        ("I'll Be Missing You", "Puff Daddy & Faith Evans"),
        ("Torn", "Natalie Imbruglia"),
        ("Tubthumping", "Chumbawamba"),
        ("Bitter Sweet Symphony", "The Verve"),
        ("Don't Speak", "No Doubt"),
        ("Everybody", "Backstreet Boys"),
        ("Men in Black", "Will Smith"),
    ],
    1998: [
        ("My Heart Will Go On", "Céline Dion"),
        ("Believe", "Cher"),
        ("Iris", "Goo Goo Dolls"),
        ("Truly Madly Deeply", "Savage Garden"),
        ("The Boy Is Mine", "Brandy & Monica"),
        ("I Don't Want to Miss a Thing", "Aerosmith"),
        ("Frozen", "Madonna"),
        ("Together Again", "Janet Jackson"),
        ("Gonna Make You Sweat", "C+C Music Factory"),
        ("Ray of Light", "Madonna"),
    ],
    1999: [
        ("...Baby One More Time", "Britney Spears"),
        ("Livin' la Vida Loca", "Ricky Martin"),
        ("Mambo No. 5", "Lou Bega"),
        ("Blue", "Eiffel 65"),
        ("Genie in a Bottle", "Christina Aguilera"),
        ("I Want It That Way", "Backstreet Boys"),
        ("Smooth", "Santana ft. Rob Thomas"),
        ("No Scrubs", "TLC"),
        ("Believe", "Cher"),
        ("Bailamos", "Enrique Iglesias"),
    ],
    2000: [
        ("Who Let the Dogs Out", "Baha Men"),
        ("It's My Life", "Bon Jovi"),
        ("Oops!...I Did It Again", "Britney Spears"),
        ("Music", "Madonna"),
        ("Beautiful Day", "U2"),
        ("It Feels So Good", "Sonique"),
        ("Stan", "Eminem ft. Dido"),
        ("Bye Bye Bye", "NSYNC"),
        ("Say My Name", "Destiny's Child"),
        ("I'm Outta Love", "Anastacia"),
    ],
    2001: [
        ("Can't Get You Out of My Head", "Kylie Minogue"),
        ("Lady Marmalade", "Christina, Lil' Kim, Mya, Pink"),
        ("Hanging by a Moment", "Lifehouse"),
        ("Fallin'", "Alicia Keys"),
        ("Drops of Jupiter", "Train"),
        ("It Wasn't Me", "Shaggy"),
        ("Thank You", "Dido"),
        ("All for You", "Janet Jackson"),
        ("Angel", "Shaggy ft. Rayvon"),
        ("Bootylicious", "Destiny's Child"),
    ],
    2002: [
        ("In da Club", "50 Cent"),
        ("Complicated", "Avril Lavigne"),
        ("Hero", "Enrique Iglesias"),
        ("Sk8er Boi", "Avril Lavigne"),
        ("Hot in Herre", "Nelly"),
        ("Whenever, Wherever", "Shakira"),
        ("A Thousand Miles", "Vanessa Carlton"),
        ("Dilemma", "Nelly ft. Kelly Rowland"),
        ("Without Me", "Eminem"),
        ("The Ketchup Song", "Las Ketchup"),
    ],
    2003: [
        ("Crazy in Love", "Beyoncé ft. Jay-Z"),
        ("In da Club", "50 Cent"),
        ("Bring Me to Life", "Evanescence"),
        ("Where Is the Love?", "Black Eyed Peas"),
        ("Numb", "Linkin Park"),
        ("Beautiful", "Christina Aguilera"),
        ("Get Busy", "Sean Paul"),
        ("Stacy's Mom", "Fountains of Wayne"),
        ("Rock Your Body", "Justin Timberlake"),
        ("Hey Ya!", "Outkast"),
    ],
    2004: [
        ("Yeah!", "Usher ft. Lil Jon & Ludacris"),
        ("Toxic", "Britney Spears"),
        ("This Love", "Maroon 5"),
        ("Burn", "Usher"),
        ("Hey Ya!", "Outkast"),
        ("My Immortal", "Evanescence"),
        ("Numb/Encore", "Linkin Park & Jay-Z"),
        ("Goodies", "Ciara ft. Petey Pablo"),
        ("Drop It Like It's Hot", "Snoop Dogg ft. Pharrell"),
        ("Somebody Told Me", "The Killers"),
    ],
    2005: [
        ("We Belong Together", "Mariah Carey"),
        ("Hollaback Girl", "Gwen Stefani"),
        ("Since U Been Gone", "Kelly Clarkson"),
        ("Gold Digger", "Kanye West ft. Jamie Foxx"),
        ("1, 2 Step", "Ciara ft. Missy Elliott"),
        ("Feel Good Inc.", "Gorillaz"),
        ("Candy Shop", "50 Cent"),
        ("Boulevard of Broken Dreams", "Green Day"),
        ("Don't Cha", "The Pussycat Dolls"),
        ("Hung Up", "Madonna"),
    ],
    2006: [
        ("Hips Don't Lie", "Shakira ft. Wyclef Jean"),
        ("Crazy", "Gnarls Barkley"),
        ("SexyBack", "Justin Timberlake"),
        ("SOS", "Rihanna"),
        ("Promiscuous", "Nelly Furtado ft. Timbaland"),
        ("Bad Day", "Daniel Powter"),
        ("Maneater", "Nelly Furtado"),
        ("Temperature", "Sean Paul"),
        ("Déjà Vu", "Beyoncé ft. Jay-Z"),
        ("Buttons", "The Pussycat Dolls ft. Snoop Dogg"),
    ],
    2007: [
        ("Umbrella", "Rihanna ft. Jay-Z"),
        ("Bleeding Love", "Leona Lewis"),
        ("Stronger", "Kanye West"),
        ("Beautiful Girls", "Sean Kingston"),
        ("Girlfriend", "Avril Lavigne"),
        ("Hey There Delilah", "Plain White T's"),
        ("Big Girls Don't Cry", "Fergie"),
        ("Cupid's Chokehold", "Gym Class Heroes"),
        ("Rehab", "Amy Winehouse"),
        ("What Goes Around...Comes Around", "Justin Timberlake"),
    ],
    2008: [
        ("Low", "Flo Rida ft. T-Pain"),
        ("Bleeding Love", "Leona Lewis"),
        ("Viva la Vida", "Coldplay"),
        ("I Kissed a Girl", "Katy Perry"),
        ("Love Story", "Taylor Swift"),
        ("Disturbia", "Rihanna"),
        ("No One", "Alicia Keys"),
        ("Lollipop", "Lil Wayne"),
        ("Paper Planes", "M.I.A."),
        ("Forever", "Chris Brown"),
    ],
    2009: [
        ("Poker Face", "Lady Gaga"),
        ("Boom Boom Pow", "Black Eyed Peas"),
        ("I Gotta Feeling", "Black Eyed Peas"),
        ("Just Dance", "Lady Gaga"),
        ("Right Round", "Flo Rida"),
        ("Single Ladies", "Beyoncé"),
        ("Paparazzi", "Lady Gaga"),
        ("Bad Romance", "Lady Gaga"),
        ("Use Somebody", "Kings of Leon"),
        ("Down", "Jay Sean ft. Lil Wayne"),
    ],
    2010: [
        ("Tik Tok", "Kesha"),
        ("Bad Romance", "Lady Gaga"),
        ("Love the Way You Lie", "Eminem ft. Rihanna"),
        ("California Gurls", "Katy Perry ft. Snoop Dogg"),
        ("OMG", "Usher ft. will.i.am"),
        ("Dynamite", "Taio Cruz"),
        ("Telephone", "Lady Gaga ft. Beyoncé"),
        ("Alejandro", "Lady Gaga"),
        ("DJ Got Us Fallin' in Love", "Usher ft. Pitbull"),
        ("Nothin' on You", "B.o.B ft. Bruno Mars"),
    ],
    2011: [
        ("Someone Like You", "Adele"),
        ("Rolling in the Deep", "Adele"),
        ("Party Rock Anthem", "LMFAO"),
        ("Moves Like Jagger", "Maroon 5 ft. Christina Aguilera"),
        ("Give Me Everything", "Pitbull ft. Ne-Yo"),
        ("Firework", "Katy Perry"),
        ("E.T.", "Katy Perry ft. Kanye West"),
        ("Born This Way", "Lady Gaga"),
        ("Super Bass", "Nicki Minaj"),
        ("Pumped Up Kicks", "Foster the People"),
    ],
    2012: [
        ("Gangnam Style", "PSY"),
        ("Somebody That I Used to Know", "Gotye ft. Kimbra"),
        ("Call Me Maybe", "Carly Rae Jepsen"),
        ("We Are Young", "fun. ft. Janelle Monáe"),
        ("Payphone", "Maroon 5 ft. Wiz Khalifa"),
        ("Titanium", "David Guetta ft. Sia"),
        ("Starships", "Nicki Minaj"),
        ("Diamonds", "Rihanna"),
        ("Whistle", "Flo Rida"),
        ("Wide Awake", "Katy Perry"),
    ],
    2013: [
        ("Blurred Lines", "Robin Thicke ft. T.I. & Pharrell"),
        ("Radioactive", "Imagine Dragons"),
        ("Get Lucky", "Daft Punk ft. Pharrell Williams"),
        ("Roar", "Katy Perry"),
        ("Can't Hold Us", "Macklemore & Ryan Lewis"),
        ("Wrecking Ball", "Miley Cyrus"),
        ("Royals", "Lorde"),
        ("Wake Me Up", "Avicii"),
        ("Counting Stars", "OneRepublic"),
        ("The Fox", "Ylvis"),
    ],
    2014: [
        ("Happy", "Pharrell Williams"),
        ("Uptown Funk", "Mark Ronson ft. Bruno Mars"),
        ("All About That Bass", "Meghan Trainor"),
        ("Shake It Off", "Taylor Swift"),
        ("Rude", "Magic!"),
        ("Stay with Me", "Sam Smith"),
        ("Dark Horse", "Katy Perry ft. Juicy J"),
        ("Chandelier", "Sia"),
        ("All of Me", "John Legend"),
        ("Fancy", "Iggy Azalea ft. Charli XCX"),
    ],
    2015: [
        ("See You Again", "Wiz Khalifa ft. Charlie Puth"),
        ("Uptown Funk", "Mark Ronson ft. Bruno Mars"),
        ("Hello", "Adele"),
        ("Lean On", "Major Lazer & DJ Snake ft. MØ"),
        ("Hotline Bling", "Drake"),
        ("The Hills", "The Weeknd"),
        ("Can't Feel My Face", "The Weeknd"),
        ("Cheerleader", "OMI"),
        ("Sugar", "Maroon 5"),
        ("Watch Me", "Silentó"),
    ],
    2016: [
        ("One Dance", "Drake ft. Wizkid & Kyla"),
        ("Cheap Thrills", "Sia ft. Sean Paul"),
        ("Closer", "The Chainsmokers ft. Halsey"),
        ("Work", "Rihanna ft. Drake"),
        ("Can't Stop the Feeling!", "Justin Timberlake"),
        ("Don't Let Me Down", "The Chainsmokers ft. Daya"),
        ("7 Years", "Lukas Graham"),
        ("Stressed Out", "Twenty One Pilots"),
        ("Panda", "Desiigner"),
        ("No", "Meghan Trainor"),
    ],
    2017: [
        ("Despacito", "Luis Fonsi & Daddy Yankee ft. Justin Bieber"),
        ("Shape of You", "Ed Sheeran"),
        ("Something Just Like This", "The Chainsmokers & Coldplay"),
        ("Believer", "Imagine Dragons"),
        ("Rockstar", "Post Malone ft. 21 Savage"),
        ("That's What I Like", "Bruno Mars"),
        ("HUMBLE.", "Kendrick Lamar"),
        ("It Ain't Me", "Kygo & Selena Gomez"),
        ("Stay", "Zedd & Alessia Cara"),
        ("Bad and Boujee", "Migos ft. Lil Uzi Vert"),
    ],
    2018: [
        ("God's Plan", "Drake"),
        ("Havana", "Camila Cabello ft. Young Thug"),
        ("In My Feelings", "Drake"),
        ("Perfect", "Ed Sheeran"),
        ("I Like It", "Cardi B, Bad Bunny & J Balvin"),
        ("Rockstar", "Post Malone ft. 21 Savage"),
        ("One Kiss", "Calvin Harris & Dua Lipa"),
        ("Girls Like You", "Maroon 5 ft. Cardi B"),
        ("Nice for What", "Drake"),
        ("Psycho", "Post Malone ft. Ty Dolla Sign"),
    ],
    2019: [
        ("Old Town Road", "Lil Nas X ft. Billy Ray Cyrus"),
        ("Bad Guy", "Billie Eilish"),
        ("Señorita", "Shawn Mendes & Camila Cabello"),
        ("Sucker", "Jonas Brothers"),
        ("7 Rings", "Ariana Grande"),
        ("Sunflower", "Post Malone & Swae Lee"),
        ("Truth Hurts", "Lizzo"),
        ("Dance Monkey", "Tones and I"),
        ("Happier", "Marshmello & Bastille"),
        ("thank u, next", "Ariana Grande"),
    ],
    2020: [
        ("Blinding Lights", "The Weeknd"),
        ("Dance Monkey", "Tones and I"),
        ("Rockstar", "DaBaby ft. Roddy Ricch"),
        ("The Box", "Roddy Ricch"),
        ("Watermelon Sugar", "Harry Styles"),
        ("Roses", "SAINt JHN"),
        ("Don't Start Now", "Dua Lipa"),
        ("Say So", "Doja Cat"),
        ("Savage Love", "Jawsh 685 & Jason Derulo"),
        ("WAP", "Cardi B ft. Megan Thee Stallion"),
    ],
    2021: [
        ("Drivers License", "Olivia Rodrigo"),
        ("Stay", "The Kid LAROI & Justin Bieber"),
        ("Levitating", "Dua Lipa"),
        ("good 4 u", "Olivia Rodrigo"),
        ("Montero", "Lil Nas X"),
        ("Peaches", "Justin Bieber ft. Daniel Caesar & Giveon"),
        ("Kiss Me More", "Doja Cat ft. SZA"),
        ("Save Your Tears", "The Weeknd"),
        ("Astronaut in the Ocean", "Masked Wolf"),
        ("Industry Baby", "Lil Nas X & Jack Harlow"),
    ],
    2022: [
        ("As It Was", "Harry Styles"),
        ("Heat Waves", "Glass Animals"),
        ("About Damn Time", "Lizzo"),
        ("Running Up That Hill", "Kate Bush"),
        ("First Class", "Jack Harlow"),
        ("Wait for U", "Future ft. Drake & Tems"),
        ("Me Porto Bonito", "Bad Bunny & Chencho Corleone"),
        ("Super Freaky Girl", "Nicki Minaj"),
        ("I Ain't Worried", "OneRepublic"),
        ("Unholy", "Sam Smith & Kim Petras"),
    ],
    2023: [
        ("Flowers", "Miley Cyrus"),
        ("Kill Bill", "SZA"),
        ("Last Night", "Morgan Wallen"),
        ("Calm Down", "Rema & Selena Gomez"),
        ("Creepin'", "Metro Boomin, The Weeknd & 21 Savage"),
        ("Anti-Hero", "Taylor Swift"),
        ("Die for You", "The Weeknd"),
        ("Vampire", "Olivia Rodrigo"),
        ("What Was I Made For?", "Billie Eilish"),
        ("Cruel Summer", "Taylor Swift"),
    ],
    2024: [
        ("Espresso", "Sabrina Carpenter"),
        ("A Bar Song (Tipsy)", "Shaboozey"),
        ("Not Like Us", "Kendrick Lamar"),
        ("Beautiful Things", "Benson Boone"),
        ("Lose Control", "Teddy Swims"),
        ("Too Sweet", "Hozier"),
        ("I Had Some Help", "Post Malone ft. Morgan Wallen"),
        ("Birds of a Feather", "Billie Eilish"),
        ("Taste", "Sabrina Carpenter"),
        ("Please Please Please", "Sabrina Carpenter"),
    ],
    2025: [
        ("Die With a Smile", "Lady Gaga & Bruno Mars"),
        ("APT.", "ROSÉ & Bruno Mars"),
        ("Luther", "Kendrick Lamar & SZA"),
        ("Sailor Song", "Gigi Perez"),
        ("Who", "Jimin"),
        ("Pink Pony Club", "Chappell Roan"),
        ("Saturn", "SZA"),
        ("Yeah Glo!", "GloRilla"),
        ("BAND4BAND", "Central Cee ft. Lil Baby"),
        ("That's So True", "Gracie Abrams"),
    ],
}


def generate_song_id(title, artist, year):
    """Generate a unique ID for a song."""
    data = f"{title}_{artist}_{year}".encode("utf-8")
    return hashlib.md5(data).hexdigest()[:22]


def generate_songs():
    """Generate song data from the fallback database."""
    print("=" * 60)
    print("BeatGuessr Quick Data Generator")
    print("=" * 60)

    contexts = load_contexts()
    all_songs = []

    for year, songs in sorted(FALLBACK_DB.items()):
        for title, artist in songs:
            song_id = generate_song_id(title, artist, year)

            song_data = {
                "id": song_id,
                "title": title,
                "artist": artist,
                "year": year,
                "context": contexts.get(str(year), f"Charts {year}"),
                # Note: These are placeholder URLs - the actual audio won't work
                # but the UI will function for testing
                "preview_url": f"https://p.scdn.co/mp3-preview/{song_id}",
                "cover_url": f"https://picsum.photos/seed/{song_id}/300/300",
                "album": f"{title} - Single",
                "spotify_url": f"https://open.spotify.com/track/{song_id}",
            }

            all_songs.append(song_data)

    # Save to file
    output_data = {
        "songs": all_songs,
        "contexts": contexts,
        "metadata": {
            "total_songs": len(all_songs),
            "generated_at": datetime.now().isoformat(),
            "year_range": [min(FALLBACK_DB.keys()), max(FALLBACK_DB.keys())],
            "note": "Generated from fallback database. Preview URLs are placeholders.",
        },
    }

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)

    print(f"\nGenerated {len(all_songs)} songs")
    print(f"Saved to: {OUTPUT_FILE}")
    print("\nYear distribution:")
    for year in sorted(FALLBACK_DB.keys()):
        print(f"  {year}: {len(FALLBACK_DB[year])} songs")

    print("\n✅ Data generation complete!")
    print("\nNote: Preview URLs are placeholders. Run the full scraper")
    print("(scrape_songs.py) to get actual Spotify preview URLs.")


if __name__ == "__main__":
    generate_songs()
